    {
        { name = "Панель 5 лвл", count = 1, id = 'AdvancedSolarPanel:BlockAdvSolarPanel', dmg = 0, chance = 1, color = 0xF6290C },
        { name = "Панель 4 лвл", count = 1, id = 'CompactSolars:CompactSolarBlock', dmg = 2, chance = 3, color = 0xF6290C },
        { name = "Рез.тростник 31/31", count = 2, id = 'IC2:itemCropSeed', dmg = 0, chance = 5, color = 0xF6290C },
        { name = "Иссушающий трутень", count = 4, id = 'Forestry:beeDroneGE', dmg = 0, chance = 5, color = 0xF6290C },
        { name = "Яйцо дракона", count = 1, id = 'minecraft:dragon_egg', dmg = 0, chance = 8, color = 0xF6290C },

        { name = "Нано Гравик", count = 1, id = 'GraviSuite:advNanoChestPlate', dmg = 1, chance = 13, color = 0xEFE80A },
        { name = "Звезда Ада", count = 1, id = 'minecraft:nether_star', dmg = 0, chance = 15, color = 0xEFE80A },
        { name = "Голова Иссушителя", count = 1, id = 'minecraft:skull', dmg = 1, chance = 15, color = 0xEFE80A },
        { name = "Ихор", count = 1, id = 'ThaumicTinkerer:kamiResource', dmg = 0, chance = 15, color = 0xEFE80A },
        { name = "Иридий", count = 1, id = 'IC2:itemOreIridium', dmg = 0, chance = 15, color = 0xEFE80A },
        { name = "Голова человека", count = 1, id = 'minecraft:skull', dmg = 3, chance = 15, color = 0xEFE80A },
        { name = "Молекулярный преобрз", count = 1, id = 'AdvancedSolarPanel:BlockMolecularTransformer', dmg = 0, chance = 15, color = 0xEFE80A },

        { name = "Ледяная материя", count = 2, id = 'dwcity:Sky_materia', dmg = 0, chance = 20, color = 0xD70AEF },
        { name = "Тёмная материя", count = 2, id = 'dwcity:Dark_materia', dmg = 0, chance = 20, color = 0xD70AEF },
        { name = "Cолнечная материя", count = 2, id = 'dwcity:Fire_materia', dmg = 0, chance = 20, color = 0xD70AEF },
        { name = "Вис материя", count = 2, id = 'dwcity:Vis_materia', dmg = 0, chance = 20, color = 0xD70AEF },
        { name = "Живая материя", count = 2, id = 'dwcity:Live_materia', dmg = 0, chance = 20, color = 0xD70AEF },
        { name = "Драк Cлиток", count = 4, id = 'DraconicEvolution:draconiumIngot', dmg = 0, chance = 20, color = 0xD70AEF },
        { name = "Драк пыль", count = 4, id = 'DraconicEvolution:draconiumDust', dmg = 0, chance = 20, color = 0xD70AEF },

        { name = "Нано Ботинки", count = 1, id = 'IC2:itemArmorNanoBoots', dmg = 27, chance = 25, color = 0x0AEFE5 },
        { name = "Нано Поножи", count = 1, id = 'IC2:itemArmorNanoLegs', dmg = 27, chance = 25, color = 0x0AEFE5 },
        { name = "Нано Грудак", count = 1, id = 'IC2:itemArmorNanoChestplate', dmg = 27, chance = 25, color = 0x0AEFE5 },
        { name = "Нано Шлем", count = 1, id = 'IC2:itemArmorNanoHelmet', dmg = 27, chance = 25, color = 0x0AEFE5 },
        { name = "Нано Сабля", count = 1, id = 'IC2:itemNanoSaber', dmg = 27, chance = 25, color = 0x0AEFE5 },
        { name = "Улучш алхим констр", count = 4, id = 'Thaumcraft:blockMetalDevice', dmg = 3, chance = 20, color = 0x0AEFE5 },
        { name = "Алхимич конструкция", count = 4, id = 'Thaumcraft:blockMetalDevice', dmg = 9, chance = 30, color = 0x0AEFE5 },
        { name = "Панель 1 лвл", count = 2, id = 'IC2:blockGenerator', dmg = 3, chance = 15, color = 0x0AEFE5 },
        { name = "Заряженный кам силы", count = 1, id = 'witchery:ingredient', dmg = 11, chance = 25, color = 0x0AEFE5 },
        { name = "Камень силы", count = 4, id = 'witchery:ingredient', dmg = 10, chance = 25, color = 0x0AEFE5 },
        { name = "Абсолютное Зло", count = 8, id = 'witchery:ingredient', dmg = 38, chance = 25, color = 0x0AEFE5 },

        { name = "Нитор", count = 16, id = 'Thaumcraft:ItemResource', dmg = 1, chance = 30, color = 0x131315 },
        { name = "Алюментум", count = 16, id = 'Thaumcraft:ItemResource', dmg = 0, chance = 30, color = 0x131315 },
        { name = "Пустотный металл", count = 8, id = 'Thaumcraft:ItemResource', dmg = 16, chance = 30, color = 0x131315 },
        { name = "Cлеза Гаста", count = 32, id = 'minecraft:ghast_tear', dmg = 0, chance = 30, color = 0x131315 },
        { name = "Фрагмент Знаний", count = 16, id = 'Thaumcraft:ItemResource', dmg = 9, chance = 30, color = 0x131315 },
        { name = "Жемчуг Эндера", count = 16, id = 'minecraft:ender_pearl', dmg = 0, chance = 30, color = 0x131315 },
        { name = "Сбаланс кристал", count = 24, id = 'Thaumcraft:ItemShard', dmg = 6, chance = 30, color = 0x131315 },
        { name = "Кластер", count = 32, id = 'Thaumcraft:blockCrystal', dmg = 6, chance = 30, color = 0x131315 },
        { name = "Изумруд", count = 16, id = 'minecraft:emerald', dmg = 0, chance = 40, color = 0x131315 },
        { name = "Алмаз", count = 16, id = 'minecraft:diamond', dmg = 0, chance = 40, color = 0x131315 },
        { name = "Редстоун", count = 24, id = 'minecraft:redstone_block', dmg = 0, chance = 50, color = 0x131315 },
        { name = "Блок Угля", count = 16, id = 'minecraft:coal_block', dmg = 0, chance = 50, color = 0x131315 },
        { name = "Таум слиток", count = 32, id = 'Thaumcraft:ItemResource', dmg = 2, chance = 40, color = 0x131315 },
        { name = "Железо", count = 32, id = 'minecraft:iron_ingot', dmg = 0, chance = 45, color = 0x131315 },
        { name = "Свинцо", count = 32, id = 'IC2:itemIngot', dmg = 5, chance = 45, color = 0x131315 },
        { name = "Cеребро", count = 32, id = 'IC2:itemIngot', dmg = 6, chance = 45, color = 0x131315 },
        { name = "Медь", count = 32, id = 'IC2:itemIngot', dmg = 0, chance = 45, color = 0x131315 },
        { name = "Золото", count = 32, id = 'minecraft:gold_ingot', dmg = 0, chance = 40, color = 0x131315 },
        { name = "Олово", count = 32, id = 'IC2:itemIngot', dmg = 1, chance = 45, color = 0x131315 },
        { name = "Адский нарост", count = 16, id = 'minecraft:nether_wart', dmg = 0, chance = 50, color = 0x131315 },
        { name = "Лазурит", count = 32, id = 'minecraft:dye', dmg = 4, chance = 50, color = 0x131315 },
        { name = "ПеченькО", count = 32, id = 'minecraft:cookie', dmg = 0, chance = 50, color = 0x131315 },
        { name = "Резина", count = 64, id = 'IC2:itemRubber', dmg = 0, chance = 50, color = 0x131315 }
    }
